services:
  # Сервис с базой данных PostgreSQL
  db:
    image: postgres:latest
    container_name: cv-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: my_cv_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cv-network
    restart: unless-stopped

  # Сервис с ASP.NET + React приложением
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cv-web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=my_cv_db;Username=admin;Password=admin
    depends_on:
      - db
    ports:
      - "5000:8080"   # HTTP -> 8080
    networks:
      - cv-network
    restart: unless-stopped

# Определяем именованный том для данных БД
volumes:
  postgres-data:

# Определяем сеть для сервисов
networks:
  cv-network:
    driver: bridge